### ISSUE TITLE
[CMS] Create rotating banner schema

### ISSUE THREAD

**Issue by sloh4137** [TACL-LYF/lyf-website-cms#2]
# Context
We want a high visibility "call to action" type of banner on the homepage. Throughout the year, we should be able to easily swap out what banners we display 

# To-Dos
- [ ] Install Sanity's media browser plugin so we can have better asset management and alt text: https://www.sanity.io/plugins/sanity-plugin-media
- [ ] Create a rotatingBanner document schema in Sanity under /schemas/documents
  - [ ] Add a required `title` field with type `string`
  - [ ] Add a required `image` field with type `image`
- [ ] Add an array of rotating banner document references to the homepage schema (allows us to pick and choose and order them) This can come later

Use `sanity start` to preview changes! 

More fields will probably be needed later but we can start with this!

**Comment by sloh4137** [comment]
Not needed
